server:
  port: 8888

spring:
  cloud:
    gateway:
      routes:
      - id: server1
        uri: http://localhost:8082
        predicates:
        - Path=/server1/**
      - id: server2
        uri: http://localhost:8083
        predicates:
        - Path=/server2/**
      - id: sso
        uri: http://localhost:8081
        predicates:
        - Path=/sso/**

hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 1000
